handbook/urls.py
from django.conf import settings
from django.conf.urls import url
from django.templatetags.static import static

from . import views
from django_pdfkit import PDFView
from django.urls import path, reverse
from .views import (
    show_category
)
import mptt_urls

from .views import tagged, detail_view

app_name = 'handbook'

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^category/(?P<hierarchy>.+)/create_(?P<pdf>.+)/$', views.show_category, name='create_pdf'),
    url(r'^post/(?P<slug>.+)/$', detail_view, name="detail"),
    url(r'^tag/(?P<slug>.+)/$', tagged, name="tagged"),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url('^private-media/(?P<path>.*)$', views.StorageView.as_view(), name='pm'),
]

hr/urls.py
from django.conf import settings
from django.conf.urls import url
from django.templatetags.static import static
from django.urls import path

from . import views

from .views import config

app_name = 'hr'

urlpatterns = [
    url(r'^ol/$', views.ol, name="hr_ol"),
    url(r'^ol/details/(?P<slug>.+)/close_ol/$', views.close_ol, name="close_ol"),
    url(r'^ol/details/(?P<slug>.+)/add_comment/$', views.add_comment, name="add_comment"),
    url(r'^ol/details/(?P<slug>.+)/$', views.details, name="hr_details"),
]

handbook/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models import Q
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor_uploader.fields import RichTextUploadingField
from private_storage.fields import PrivateFileField
from private_storage.storage.files import PrivateFileSystemStorage
from taggit_selectize.managers import TaggableManager
from django.urls import reverse
from autoslug import AutoSlugField
from solo.models import SingletonModel
import random
from django.conf import settings

DEFAULT_SINGLETON_INSTANCE_ID = 1


def slugify_function(content):
    for c in content:
        if c == '_':
            return content
    rand = random.randint(1, 10000)
    return content.lower() + '_' + str(rand)


class PostManager(models.Manager):
    use_for_related_fields = True

    def search(self, query=None):
        qs = self.get_queryset()
        if query:
            or_lookup = (Q(title__icontains=query) | Q(content__icontains=query) | Q(tags__name__icontains=query))
            qs = qs.filter(or_lookup)
        return qs


class General(models.Model):
    general_groups_admin = models.ForeignKey(Group, related_name='hadnbook_general_groups_admin',
                                             verbose_name='Администратор группы',
                                             on_delete=models.CASCADE, null=True)

    general_groups = models.ForeignKey(Group, related_name='hadnbook_general_groups',
                                       verbose_name='Разрешение для группы',
                                       on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Группа доступа'
        verbose_name_plural = 'группа доступа'

    def __str__(self):
        return str(self.general_groups)


storage = PrivateFileSystemStorage(
    location='media/private-media/handbook/',
    base_url='handbook/private-media/handbook'
)


class AttachmentsModel(models.Model):
    file = PrivateFileField("Файл", storage=storage, null=True)
    date_edit = models.DateTimeField('Дата изменения', auto_now=True, null=True)
    attachments_model = models.ForeignKey('Post', null=True, blank=True, related_name='handbook_post_model',
                                          on_delete=models.CASCADE, verbose_name='Пост')

    def get_absolute_url(self):
        return "/handbook/private-media/handbook/"

    def __str__(self):
        return self.attachments_model.title

    class Meta:
        verbose_name = 'прикрепленный файл'
        verbose_name_plural = 'Прикрепленные файлы'


class Post(models.Model):
    title = models.CharField('Заголовок', max_length=150)
    category = TreeForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE, verbose_name='Привязка к '
                                                                                                        'меню')
    content = RichTextUploadingField('Содержание')
    date_create = models.DateTimeField('Дата создания', auto_now_add=True)
    date_edit = models.DateTimeField('Дата изменения', auto_now=True)
    slug = AutoSlugField(slugify=slugify_function)
    published = models.BooleanField(default=True, verbose_name='Выводить в списке?')
    tags = TaggableManager()
    post_groups = models.ManyToManyField(Group, related_name='post_groups', verbose_name='Разрешение для групп')
    objects = PostManager()

    def get_absolute_url(self):
        return '/handbook/category/%s/' % self.slug

    def get_absolute_url_tags(self):
        return '/handbook/tag/'

    class Meta:
        ordering = ('title',)
        verbose_name = 'информацию на странице'
        verbose_name_plural = 'Информация на страницах'

    def __str__(self):
        return self.title


class Category(MPTTModel):
    name = models.CharField(max_length=50, verbose_name='Название', unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
                            on_delete=models.CASCADE, verbose_name='Привязка к меню')
    slug = AutoSlugField()
    objects = PostManager()

    def get_bug_count(self):
        return Post.objects.filter(category=self).count()

    def get_absolute_url(self):
        return reverse('handbook', kwargs={'path': self.get_path()})

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except:
            ancestors = []
        else:
            ancestors_slug = [i.slug for i in ancestors]
            ancestors_name = [i.name for i in ancestors]
            ancestors = [i.slug for i in ancestors]

        c = []
        c2 = []
        c3 = ['|']

        for i in range(len(ancestors)):
            c.append('/'.join(ancestors_slug[:i + 1]))
            c2.append('/'.join(ancestors_name[:i + 1]))
            c[i] = c[i] + c3[0] + c2[i]
        return c

    class Meta:
        ordering = ('tree_id', 'lft')
        verbose_name = 'дополнительное меню'
        verbose_name_plural = 'Дополнительное меню'
        unique_together = ('parent', 'slug',)

    def __str__(self):
        return self.name

handbook/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'tags',
        ]

handbook/views.py
import os
import random
import sys

import pdfkit
from django.core.exceptions import PermissionDenied
from private_storage.views import PrivateStorageView

from .models import Category, AttachmentsModel
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Post
from taggit.models import Tag
from django.template.loader import render_to_string
from django.conf import settings
from .utils import group_required
from blog_mks.utils import group_required_post
from blog_mks.views import h404


@group_required()
def create_pdf(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    return render(request, 'handbook/detail.html', context)


@group_required()
def detail_view(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    return render(request, 'handbook/detail.html', context)


@group_required()
def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Post.tags.most_common()[:4]
    creators_list = group_required_post(request)
    posts = Post.objects.filter(tags=tag, post_groups__name__in=creators_list, published=True).distinct()

    context = {
        'tag': tag,
        'common_tags': common_tags,
        'posts': posts,
        'menu_items': Category.objects.all(),
        'menu_items_filter': Category.objects.filter(
            post__published=True,
            post__post_groups__name__in=creators_list,
        ).distinct(),
        'menu_items_post_count': posts.count(),
    }
    return render(request, 'handbook/tagged.html', context)


@group_required()
def show_category(request, hierarchy=None, pdf=None):
    category_slug = hierarchy.split('/')
    parent = None
    root = Category.objects.all()
    creators_list = group_required_post(request)

    for slug in category_slug[:-1]:
        parent = root.get(parent=parent, slug=slug)
    try:
        instance = Category.objects.get(parent=parent, slug=category_slug[-1])
        instance = instance.post_set.filter(post_groups__name__in=creators_list, published=True).distinct()
    except:
        try:
            instance = Post.objects.filter(
                slug=category_slug[-1],
                post_groups__name__in=creators_list,
                published=True).distinct()
            posts = Post.objects.filter(post_groups__name__in=creators_list, published=True).distinct()
            menu_items_post_count = posts.count()

            if instance.exists():
                instance = get_object_or_404(Post, slug=category_slug[-1])
                if pdf:
                    content = render_to_string("handbook/create_pdf.html", {
                        'instance': instance
                    })

                    content = content.replace("src=\"", "src=\"%s" % settings.BASE_URL)
                    content = content.replace("href=\"", "href=\"%s" % settings.BASE_URL)
                    file_path = 'media/tmp/handbook/PDF_%s.pdf' % random.randrange(100000)
                    pdfkit.from_string(content, file_path)

                    if os.path.exists(file_path):
                        with open(file_path, 'rb') as fh:
                            response = HttpResponse(fh.read(), content_type="application/pdf")
                            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                            return response

                menu_items = Category.objects.all()
                menu_items_filter = Category.objects.filter(
                    post__published=True,
                    post__post_groups__name__in=creators_list,
                ).distinct()
                return render(request, "handbook/post_detail.html", {
                    'instance': instance,
                    'menu_items': menu_items,
                    'menu_items_filter': menu_items_filter,
                    'menu_items_post_count': menu_items_post_count,
                })
            else:
                return h404(request)
        except:
            return h404(request)

    else:
        post = Post.objects.filter(
            post_groups__name__in=creators_list,
            category__slug=category_slug[-1],
            published=True).distinct()
        menu_items = Category.objects.all()
        menu_items_filter = Category.objects.filter(
            post__published=True,
            post__post_groups__name__in=creators_list,
        ).distinct()
        menu_items_post_count = post.count()

        return render(request, 'handbook/categories.html', {
            'posts': post,
            'menu_items': menu_items,
            'menu_items_filter': menu_items_filter,
            'menu_items_post_count': menu_items_post_count,
        })


@group_required()
def post_list(request):
    creators_list = group_required_post(request)

    posts = Post.objects.filter(post_groups__name__in=creators_list, published=True).distinct()
    menu_items = Category.objects.all()
    menu_items_filter = Category.objects.filter(
        post__published=True,
        post__post_groups__name__in=creators_list,
    ).distinct()
    menu_items_post_count = posts.count()
    return render(request, "handbook/categories.html", {'posts': posts,
                                                        'menu_items': menu_items,
                                                        'menu_items_filter': menu_items_filter,
                                                        'menu_items_post_count': menu_items_post_count,
                                                        })


class StorageView(PrivateStorageView):

    def get(self, request, *args, **kwargs):
        private_file = self.get_private_file()
        instance = ''

        if not self.can_access_file(private_file):
            raise PermissionDenied(self.permission_denied_message)
        else:
            creators_list = group_required_post(request)
            filename = self.get_content_disposition_filename(private_file)
            f1 = AttachmentsModel.objects.all()
            for fn in f1:
                f = AttachmentsModel.objects.filter(file=filename)
                for f2 in f:
                    f3 = f2.attachments_model.id
                    instance = Post.objects.filter(
                        id=f3,
                        post_groups__name__in=creators_list).distinct()

        if not private_file.exists():
            return self.serve_file_not_found(private_file)
        elif not instance:
            raise Http404("Файл не найден")
        else:
            return self.serve_file(private_file)

templates/handbook/base.html
{% extends 'main.html' %}
{% load mptt_tags %}
{% load static %}
{% load namify %}
{% csrf_token %}
{% block content_left_menu %}
{% set break = 0 %}
<div class="container-fluid">
		<div class="content">
			<div class="row">
                <div class="col-lg-3">
                    <div>
                        <div id="tree1" class="bstreeview">
                            <ul>
                                {% recursetree menu_items %}
                                    <li>
                                        {% for m in menu_items_filter %}
                                            {% if  node.id ==  m.id %}
                                                <a href="{{ node.get_absolute_url }}">
                                                    {{ node.name }}</a>
                                                {% set break = 1 %}
                                            {% elif forloop.last  and break == 0%}
                                                <spam class="bstreesk">{{ node.name }}</spam>
                                            {% endif %}
                                        {% endfor %}
                                        {% if  not node.is_leaf_node %}
                                            <ul class="children">{{ children }}</ul>
                                        {% endif %}
                                    </li>
                                {% endrecursetree %}
                            </ul>
                        </div>
                    </div>
                </div>
{% endblock %}
{% block content %}
{% endblock %}

{% block css %}
    <link href="{% static 'site/css/handbook/main.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'site/css/bstreeview.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'site/css/regulations/tablets.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block scripts %}
    <script src="{% static 'site/js/handbook/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script src="{% static 'site/js/bstreeview.js' %}"></script>
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{% endblock %}

templates/handbook/categories.html
{% extends 'handbook/base.html' %}
{% load mptt_tags %}
{% load static %}
{% load namify %}
{% block content %}
    <div class="col-lg-9 cont">
        {% if posts %}
            {% for i in posts %}
                <div class="row mblock">
                    <div class="col">
                        <div class="url_categoty">
                            <ul class="breadcrumbs">
                                <li><a href="/">--------</a></li>
                            {% for i2 in i.category.get_slug_list %}
                                <li><a href="/handbook/category/{{ i2 | get_slug }}/">{{ i2 | get_name }}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                        <a href="{% url 'handbook:category' i.slug %}">
                            <div class="card-divider">
                                <strong class="cke_item_title">{{ i.title | truncatechars:150}}</strong>
                            </div>
                        </a>
                            <div class="card-section">
                                <small>{{ i.publish}} </small>
                            </div>
                        <hr>
                        <div class="card-tags">
                            Используемые теги:
                            {% for tag in i.tags.all %}
                                {% if forloop.last %}
                                    <a href="{% url 'handbook:tagged' tag.slug %}" class="">{{ tag }}</a>
                                {% else %}
                                    <a href="{% url 'handbook:tagged' tag.slug %}" class="">{{ tag }},</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="row mblock">
                <div class="col">
                    <div class="card-divider">
                        <strong class="cke_item_title">Нет результатов</strong>
                    </div>
                    <br>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/handbook/create_pdf.html
{% extends 'handbook/base.html' %}
{% load mptt_tags %}
{% load static %}
{% load namify %}
{% block content_left_menu %}{% endblock %}
{% block content %}
<div class="col-lg-9 cont">
    <div class="row mblock">
        <div class="col">
            <div class="url_categoty">
                <ul class="breadcrumbs">
                        <li><a href="/">--------</a></li>
                        {% for i in instance.category.get_slug_list %}
                           <li><a href="/handbook/category/{{ i | get_slug }}/">{{ i | get_name }}</a></li>
                        {% endfor %}
                        <li><a href="/">{{ instance.title}}</a></li>
                </ul>
            </div>
            <div class="cke_editable cke_editable_themed cke_contents_ltr cke_show_borders">{{ instance.content | safe }}</div>
            <hr>
            <div>
                Дата редактирования: {{ instance.date_edit }}
            </div>
            <div class="card-tags">
                Используемые теги:
                <span  class="post_tags">
                    {% for p in instance.tags.all %}
                        {% if forloop.last %}
                            <a href="{% url 'handbook:tagged' p.slug %}" class="" target="_blank">{{ p }}</a>
                        {% else %}
                            <a href="{% url 'handbook:tagged' p.slug %}" class="" target="_blank">{{ p }},</a>
                        {% endif %}
                    {% endfor %}
                </span>
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}

templates/handbook/post_detail.html
{% extends 'handbook/base.html' %}
{% load mptt_tags %}
{% load static %}
{% load namify %}
{% load attachments_tags %}
{% block content %}
    <div class="col-lg-9 cont">
        <div class="row mblock">
            <div class="col">
                <div class="url_categoty">
                    <ul class="breadcrumbs">
                            <li><a href="/">--------</a></li>
                            {% for i in instance.category.get_slug_list %}
                               <li><a href="/handbook/category/{{ i | get_slug }}/">{{ i | get_name }}</a></li>
                            {% endfor %}
                            <li><a href="">{{ instance.title}}</a></li>
                    </ul>
                </div>
                <div class="cke_editable cke_editable_themed cke_contents_ltr cke_show_borders">{{ instance.content | safe }}</div>
                <hr>
                <div>
                    Дата редактирования: {{ instance.date_edit }}
                </div>
                <div class="card-tags">
                    Используемые теги:
                    <span  class="post_tags">
                        {% for p in instance.tags.all %}
                            {% if forloop.last %}
                                <a href="{% url 'handbook:tagged' p.slug %}" class="">{{ p }}</a>
                            {% else %}
                                <a href="{% url 'handbook:tagged' p.slug %}" class="">{{ p }},</a>
                            {% endif %}
                        {% endfor %}
                    </span>
                </div>
                <div>
                    Скачать статью:
                    <a href="create_pdf/" class="create_pdf" target="_blank">PDF</a>
                </div>
                <div>
                {% if instance.handbook_post_model.all.count > 0 %}
                    <table class="table">
                    Прикрепленные файлы ({{ instance.handbook_post_model.all.count }}):
                        {% for att in instance.handbook_post_model.all %}
                            <tr class="simple_view">
                                <td><a href="{{ att.get_absolute_url }}{{ att.file }}" class="">{{ att.file }}</a></td>
                                <td align="right">{{ att.date_edit }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
                </div>
                <br>
            </div>
        </div>
    </div>
{% endblock %}

templates/handbook/tagged.html
{% extends 'handbook/base.html' %}
{% load mptt_tags %}
{% load static %}
{% load namify %}
{% block content %}
    <div class="col-lg-9 cont">
    <div class="card-tags-common">
        <p>
            Похожие теги:
            {% for mt in common_tags %}
                <a href="{% url 'handbook:tagged' mt.slug %}" class="badge">{{ mt }}</a>
            {% endfor %}
        </p>
    </div>
        {% if posts %}
            {% for i in posts %}
                <div class="row mblock">
                    <div class="col">
                        <div class="url_categoty">
                            <ul class="breadcrumbs">
                                <li><a href="/">--------</a></li>
                            {% for i2 in i.category.get_slug_list %}
                                <li><a href="/handbook/category/{{ i2 | get_slug }}/">{{ i2 | get_name }}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                        <a href="{% url 'handbook:category' i.slug %}">
                            <div class="card-divider">
                                <strong class="cke_item_title">{{ i.title | truncatechars:150}}</strong>
                            </div>
                        </a>
                            <div class="card-section">
                                <small>{{ i.publish}} </small>
                            </div>
                        <hr>
                        <div class="card-tags">
                            Используемые теги:
                            {% for tag in i.tags.all %}
                                {% if forloop.last %}
                                    <a href="{% url 'handbook:tagged' tag.slug %}" class="">{{ tag }}</a>
                                {% else %}
                                    <a href="{% url 'handbook:tagged' tag.slug %}" class="">{{ tag }},</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <div class="row mblock">
                    <div class="col">
                        <div class="card-divider">
                            <strong class="cke_item_title">Нет результатов</strong>
                        </div>
                        <br>
                    </div>
                </div>
        {% endif %}
    </div>
{% endblock %}